import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { signIn, signOut, useSession } from 'next-auth/react'

import { api } from '../utils/api'
import { ThemeToggle } from '@/components/ThemeToggle'
import { Button } from '@/components/Button'
import AuthShowcase from '@/components/AuthShowcase'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next 13 - T3 - Crud</title>
        <meta
          name="description"
          content="A Crud using Next 13 generated by create-t3-app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#8e5bd6] to-[#6065bd] dark:from-[#2e026d] dark:to-[#15162c]">
        <div className="navbar flex justify-between bg-base-100">
          <ThemeToggle />
          <AuthShowcase />
        </div>
      </main>
    </>
  )
}

export default Home
