import Header from 'next/head'

type HeadProps = {
  title: string
}

export const Head = ({ title }: HeadProps) => (
  <Header>
    <title>{title}</title>
    <meta
      name="description"
      content="A Crud using Next 13 generated by create-t3-app"
    />
    <link rel="icon" href="/favicon.ico" />
  </Header>
)
